[tool.poetry]
name = "dvmn_async"
version = "0.1.0"
description = "console game"
authors = ["art <monkeyking1984@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
